name: npm-publish
'on':
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm ci --legacy-peer-deps --ignore-scripts
      - name: Build
        run: npm run build:production
      - name: Publish
        run: |
           cd dist
           ls -ltra .
           npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
