name: workflow

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: |
          bun install --frozen-lockfile
          bun run build

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Amsterdam
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: |
          version=${{ github.ref_name }}
          sed -i "s/{{PLACEHOLDER_VERSION}}/${version}/" ./src/version.ts
          cat ./src/version.ts
      - run: |
          bun install --frozen-lockfile
          bun run build
      - run: |
          cp README.md ./dist
          cp LICENSE ./dist
          cp package.json ./dist
          cd dist && npx npm publish
